# Generated by Django 5.2 on 2025-04-19 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('tipo_tunel', models.CharField(choices=[('estatico', 'Estático'), ('dinamico', 'Dinâmico')], max_length=10)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual_tunel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('periodicidade_minutos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='monitoramento.ativo')),
            ],
        ),
    ]
